Prefix all errors with error word

diff --git a/the b/the
--- a/the
+++ b/the
@@ -4,7 +4,7 @@ base_path="$(pwd -P)"
 endpoint_url="https://the.delasy.com"
 
 throw () {
-  >&2 echo "$@"
+  >&2 echo "Error: $1"
   exit 1
 }
 
@@ -42,7 +42,7 @@ for (( i=1; i <= "$#"; i++ )); do
     elif [ "$arg" == "lex" ]; then
       is_lex=true
     else
-      throw "Unknown option: $arg"
+      throw "Unknown option '$arg'"
     fi
   elif (( i == 2 )); then
     file_dir="$(cd "$base_path/$(dirname "$arg")" && pwd -P)"
@@ -57,7 +57,7 @@ for (( i=1; i <= "$#"; i++ )); do
       throw "File '$file_path' does not exists"
     fi
   else
-    throw "Unknown option: $arg"
+    throw "Unknown option '$arg'"
   fi
 done
 
